### ISSUE TITLE
Order placing

### ISSUE THREAD

**Issue by Korbrent** [HeartAttackCat/TomcatDonutStore#12]
### Client-side: 
Functionality needs to be implemented which takes user input and keeps a running tab on the current cart of the user. After the user checks out, the client-side needs to POST to the servlet with the order and await a response. The Servlet will respond with the OrderID, TotalPrice and TotalQuantity, and the client-side should then display this information.
### Server-side:
Once the servlet receives an order from the client, it should create an order entry in the database. This should be split into two Java classes, one which handles communicating with the client and another which handles communicating with MySQL, similar to our previous implementation. 
- the client handler will host a REST endpoint which awaits a POST of JSON data. Once it receives the JSON, it extracts necessary information (DonutNames & Quantities) and creates an order using the MySQL handler. (*read the next bullet point, then return here for optimal reading flow*) After entering the order in the database using the MySQL handler, the servlet should respond to the client with the client's OrderID, TotalPrice, TotalQuantity and other information you deem necessary. _It is important to not use the total passed by the client as it **may be wrong**_. Do all calculations on the serverside.
-  The MySQL handler will filter and format statements for creating a new entry in the order table and will respond back to the client handler with an OrderID and any other relevant information. It is **extremely important** to filter and control the MySQL statements before sending them to the database. Clever tricksters may try and use SQL injections to do nefarious deeds!

**Comment by Korbrent** [comment]
The current JavaScript assumes there exists a div on the current HTML document called `cart-window` and updates the internal HTML of said div. 

The internals of the div are structured as follows:
```html
<div id='cart-window'>
    <div class=['cart-item', 'total-item']>
        <h3>Total <\h3>
        <h4>Quantity: {quantity} <\h4>
        <h4>Total Price: {$.2f} <\h4>
    <\div>
    <div class='cart-item'>
        <h3>{donut.name}<\h3>
        <h4>Quantity: {donut.quantity}<\h4>
        <h4>Price: {donut.price}<\h4>
    <\div>
    <!-- Repeat for as many donuts in cart-->
    <button class='checkout-button' onclick='checkout_command()'>Checkout<\button>
<\div>
```
Typing this out, I realize I should probably have two different price entries per donut, one that displays the price per single donut, and another displaying the price given the quantity. Oh well, simple fix.

**Comment by Korbrent** [comment]
Session trackers on the serverside can be used to manage persistence from the server end as well, in case we want to verify users and assign userids in a future change

**Comment by HeartAttackCat** [comment]
While using JS and using JSON would be a modern approach to full stack development. In web dev to make the development easy and concurrent with the class we should use HttpSession object to store orders and to retrieve order information. This means that JS and JSON will be ditched for JSP and HttpSession Hashtable.

The approach to the shopping cart is to track an array list cookie that holds an arraylist<order> object. Then when the user commits there final purchase then we can use a servlet and the j-connector for mysql.

Once again your approach is modern and I like it, however after talking with the professor we should keep the scope to the tools they have focused on. This also will help our teammates as they already worked with and developed under the model of JSP.

**Comment by Korbrent** [comment]
We can simply do both? Post the order to the server via JSON, and on the server side use an HttpSession to manage a cookie containing the UUID for the client which is stored in a table on the serverside.

**Comment by HeartAttackCat** [comment]
I fail to understand exactly how this addresses the issue with keeping the project consistent with the other team members. JSON and JS works but it doesn't help the fact that our other team members know JSP and Java not JS and JSON. Having the menu and the display page work with JSP and Java then the cart being in JS and JSON seems incredibly inconsistent and would make the project more messy and harder to follow.
