### ISSUE TITLE
Inserting into Database

### ISSUE THREAD

**Issue by MoonBasedKas** [HeartAttackCat/TomcatDonutStore#14]
We need to implement functionally to insert values into a database. 

To achieve, the current suggestion is to expand the functionality of the dataBaseFetcher class to also be capable of inserting values into the database. Done similarly to how it's currently implemented with prepared statements. I've discussed with Hunter and their suggestion was to introduce an order class, a cart class, a customer class, and adding new methods to DB fetcher to insert values.

- The order class would contain a donut object and a quantity.

- The customer class will contain all of our customer information. We will need to have the attributes firstName, lastName, zipCode, customerAddress, phoneNumber, email, cardID.

- The cart class would contain an array list of order objects.

- For inserting values, we will need the following methods: insertOrder(cart), insertCustomer(customer), and insertDonut(donut). Managing the database for inventory will be a separate issue.

The insertOrder() method would need to do the following: 

- Generate a unique order ID. Due to the size of the project, we can get away by generating a random number from 1-10,000. A better approach would be using a select statement to obtain the max ID, then adding one. Due to order ID not being unique I cannot make it keyed and auto increment.

- We need to make a series of insertions, each unique donut in the order will need to be its own entry in the table. They will have the same ID where the only information that will change with each entry is the donut information, the quantity, and the donut price.

insertCustomer() will be similar, however we do not have to worry about managing customer ID's. We can make the field keyed and enable auto incrementing. 

insertDonut() this will take our already defined donut class and simply add those values to the table. The donut object only exists within the polishingmnpg branch.

**Comment by Korbrent** [comment]
> Due to the size of the project, we can get away by generating a random number from 1-10,000.

This may cause issues later, as it is likely intended for Order IDs to originate at zero and increment per order, per day. Not that the functionality is implemented yet, but when it comes time to implement extended employee functionality, it may be difficult to order the orders in a sequential manner if the indexes themselves are not sequential. 
I can see two ways to "fix" this. 
1. Like you said, manually get the max ID for the day and increment by one. 
2. Just add another column for a unique ID that increments regardless of the day and doesnt reset, and use this as our sorting index. 

> The donut object only exists within the polishingmnpg branch

Sounds like the main branch needs to be caught up

**Comment by MoonBasedKas** [comment]
> This may cause issues later, as it is likely intended for Order IDs to originate at zero and increment per order, per day. 

That is a good concern you bring up. I think approach 1 should be fine as we can just add a condition when querying information for whatever date we want to look at.

> Sounds like the main branch needs to be caught up

Agreed. The main branch should be up-to-date now.

**Comment by MoonBasedKas** [comment]
Database fetcher's updated functionality should be working now, just needs more debugging before committing a proper merge with main.

**Comment by MoonBasedKas** [comment]
Tested completed, inserting appears to be working as intended.
