### ISSUE TITLE
MySQL DB Design

### ISSUE THREAD

**Issue by Korbrent** [HeartAttackCat/TomcatDonutStore#2]
One member needs to write a MySQL script to initialize our DB (or just build the DB by hand, but a script is easily reproducible).

**Comment by HeartAttackCat** [comment]
Not done yet as future changes may need to be done for other milestones in the project.

**Comment by MoonBasedKas** [comment]
Add a customer database. This will include vital customer info and allow us to better organize our database. Entry requirements are name, address, phone #, and email. To differentiate customers, an ID will be implemented as a key value. The database will handle generating new ID's.

This will require updating the order table. We will need to replace customer info with a customer ID. Another suggestion is to add a competition status, which would be a boolean value. Upon completion of an order, it will update every entry in the table's completion to true.

**Comment by MoonBasedKas** [comment]
Update donut ID to be the primary key of the database and allow it to auto-increment on NULL.

The main benefit is when inserting donuts into the database it will be significantly easier as we will not need to make another query to generate a new ID and do not have to generate the ID server side.
