### ISSUE TITLE
Tray and expanded order management on the Database

### ISSUE THREAD

**Issue by MoonBasedKas** [HeartAttackCat/TomcatDonutStore#21]
We need to introduce more functionality when operating on the database and managing trays. We need to introduce the following three methods for tray management: createTray(Integer), veiwTrays() and removeFromTray(Order). Finally, for order management, we will need to introduce two new methods as well. fetchOrders() and completeOrder(Integer). Finally, we will need to create a Tray object type.

Datatypes:
-----
Tray:
Will contain the following information as attributes. Could also seperate the Tray wrapper into two seperate datatypes as trays that are baking will have different attributes from ones that have finished.
  1. id unique to the tray: String
  2. quantity: Integer
  3. donut id: Integer
  4. startBakingTime: String
  5. endBakingTime: String
  6. expireTime: String
-----
Methods:
-----

createTray(Integer): boolean
- This method will create a tray of a given donut type.
- A tray has the following parameters it must fill in the database:
  1. id unique to the tray (We can key the database and have it auto generate this for us).
  2. quantity set to 20.
  3. donut id.
  4. startBakingTime this will be the time when the donut was put in the oven.
  5. endBakingTime this will be the time of completion 2 hours later.
  6. expireTime this will be two days after the date we've started baking.
-----
viewTrays(): ArrayList<Tray>
- This will perform a select on the database for trays that have not yet expired.
- Return an Array List of tray objects. The tray object will contain the database attributes for each tray within the database.
-----
removeFromTray(Order): boolean
- This first call viewTrays(). Using the array list it will subtract from the quantity within each Tray until one of the two scenarios:
  1. Order has been satisfied.
  2. Order does not have enough donuts to satisfy the request.
    - The program will auto generate the required trays to fulfill the order. It is assumed the employees are in the process of satisfying the requirements or already have.
-----
fetchOrders(): ArrayList<Cart>
- Return an ArrayList of carts for every order that is currently marked incomplete.
- Each cart object encapsulates an ArrayList of Orders unique to an order.
  - TODO update cart to have an id parameter which will only be filled upon fetching.
-----
completeOrder(Integer): boolean
- Takes in a given integer and will mark every order with the given id as completed.
  - Assumes that each order is completed within the same day.
- Calls removeFromTray() for each donut entry to update inventory as required.
-----
completeOrder(Integer, String): boolean
- Takes in a given integer which is the order id.
- Takes in a given String which will represent a date in YYYY-MM-DD format.
- Calls removeFromTray() for each donut entry to update inventory as needed.
-----

**Comment by MoonBasedKas** [comment]
Will need a DB table for the current inventory and the baking inventory. We will need to determine a period or time for when we will want to update this.

**Comment by MoonBasedKas** [comment]
Period: may want to set it as when an admin or employee logs in to update the time and check for cooked donuts/stale and alert employee. Split up modify database fetcher and the queries. One will do the db query and another will make a wrapper for calling/fetching for determine which ones are stale and wrap into a class separately.



`select * from bakedDonuts where date > date.now();`

`select * from bakingDonuts where endbaketime < date.now();`

Will need to update generate stales report.

**Comment by MoonBasedKas** [comment]
@Korbrent 
I will need you to write a Tray wrapper and a few methods for DBFetcher. You may want to write two separate Tray wrappers, one for trays in the inventory and one for Trays that are currently baking.

Then I will need the following methods in DB Fetcher:
- obtainBakingTrays(): ArrayList<Tray>
  - Obtains all trays that are currently baking.
- obtainInventory(): ArrayList<Tray>
  - Obtains all trays that are currently in the inventory and not expired.

**Comment by Korbrent** [comment]
Alright, I am looking through the specifications and am a bit confused on what you are expecting from the class.

Here is my current interpretation:
- I will create a class `Tray.java` responsible for managing the current inventory bake times and expire times.
- I will implement methods `public static List<Tray> getBakingTrays()`, `public static List<Tray> getInventoryTrays()`, and `public static List<Tray> getStaleTrays()`
- If I remember correctly, according to the assignment specifications, a tray has a max size of donuts, so when constructing a new tray, I will ensure there are no more than the max quantity. So, I will adjust the default constructor s.t. `public Tray(int donutID, int quantity)`. (I haven't checked to verify this claim and am currently running late to class to type this out lmao)
- As for the parameters making up the `Tray` object, I am in agreement. 

Also, I will be implementing `Tray` as an abstract class which will be implemented by `BakingTray` and `InventoryTray`.

**Comment by MoonBasedKas** [comment]
I agree with your interpretation. I believe that should satisfy the assignment requirements.

**Comment by Korbrent** [comment]
Just realized I wasn't assigned. Oopsies. 
Anyways, a branch is now up and linked to this issue. I have class soon, so I just pushed what I have so far.

**Comment by Korbrent** [comment]
Sitting in class, thinking about this more.
I need to update the classes to add and remove from the database, however now I am trying to think of the best way to do this. 

Right now my current thought process is this:
- Insert into DB during construction of the tray. 
- Update/Remove en masse from DB when calling `updateBakedTrays()` and `updateStaleTrays()`
- Load all trays in db on servlet startup and keep a `static List<Tray>` of trays.

Alternatively, we could just keep re-fetching from the database each time Tray methods are queried...

Oh well, this class has drained my soul and I am struggling to stay awake.

**Comment by Korbrent** [comment]
So we are not using String UUIDs for Trays. Got it

**Comment by MoonBasedKas** [comment]
Yes we are using integers I did not mean to write string lol.
