### ISSUE TITLE
addDonut function in Cart.java

### ISSUE THREAD

**Issue by HeartAttackCat** [HeartAttackCat/TomcatDonutStore#32]
The Cart model needs a function to add a donut to the order list. The function should contain 2 parameters, donut id and quantity of the donut type. It should check the orders list if the donut already exists and should increase the order quantity by the quantity passed through the function.

`boolean addDonut(int donutID, int quantity);`

Please and thank you.

**Comment by Korbrent** [comment]
@HeartAttackCat Code is pushed, awaiting PR now. Feel free to close & comment when accepted

**Comment by Korbrent** [comment]
Pull me in
![image](https://github.com/user-attachments/assets/34ceb186-a38a-4c5d-8406-e80f2a2fb23c)
