### ISSUE TITLE
Generating Admin Reports

### ISSUE THREAD

**Issue by HeartAttackCat** [HeartAttackCat/TomcatDonutStore#57]
Admin.jsp needs to have a date field and an option field that lets you select stale donut report or sales donut report.
Then create SalesReport.jsp that makes a Sales Report.
Then create StalesReport.jsp that makes a Stales Report.

Use backend wrapper to get sales or stale donut information.

**Comment by MoonBasedKas** [comment]
Functionality added just needs CSS
