### ISSUE TITLE
UML diagrams and Documentation

### ISSUE THREAD

**Issue by MoonBasedKas** [HeartAttackCat/TomcatDonutStore#70]
As required by the project we must diagrams. We will need to create the following diagrams:
Class diagrams
Use case
Sequence diagram
 - NOTE: submission page says only the customer but the project description says sequence diagrams. Not sure what is wanted.
-----
**Documentation**
Should just be a project description that describes what the project does and how its done. Write a latex file and compile to a PDF for this.
-----
**Database**
We need to prepare the database for when we present and also insert in more sample entries. Preadd some donuts that will not expire before the presentation into inventory. Then perhaps add a few incomplete orders into dOrder.

**Comment by benimaru-afk** [comment]
I added a readme explaining the project, requirements and general workload of everyone in the group in the documentation branch
